input {
  file {
    path => "/usr/share/logstash/app-logs/application.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    stat_interval => "1 second"

    codec => json {
      ecs_compatibility => "disabled"
    }
  }
}

filter {
  mutate {
    add_field => {
      "application" => "log-analytics-service"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "application-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}