input {
  tcp {
    port => 5000
    codec => json_lines {
      ecs_compatibility => "disabled"
    }
  }
}

filter {
  mutate {
    add_field => {
      "application" => "log-analytics-service"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "application-logs-%{+YYYY.MM.dd}"
  }

  s3 {
    region => "us-west-1"
    bucket => "log-analytics-sravanthi-2026"
    prefix => "application-logs/year=%{+YYYY}/month=%{+MM}/day=%{+dd}/"

    validate_credentials_on_root_bucket => false

    rotation_strategy => "time"
    time_file => 1
    temporary_directory => "/usr/share/logstash/data/s3-temp"

    codec => json_lines
  }

  stdout {
    codec => rubydebug
  }
}